#!/bin/bash

# ============================================
# THUNDERBIRD BIZFLY INSTALLER - FIXED VERSION
# Version: 4.0 - Hoạt động 100%
# ============================================

set -e

# Màu sắc
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

clear
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     🚀 THUNDERBIRD BIZFLY INSTALLER v4.0                ║${NC}"
echo -e "${BLUE}║     ✅ ĐÃ SỬA LỖI SETUP WIZARD                          ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ============================================
# 1. KIỂM TRA MÔI TRƯỜNG
# ============================================
echo -e "${BLUE}[1/5] 🔍 Kiểm tra môi trường...${NC}"

if ! command -v thunderbird &> /dev/null; then
    echo -e "  ${YELLOW}⚠️${NC} Thunderbird chưa cài, đang cài đặt..."
    sudo apt update -qq
    sudo apt install -y thunderbird > /dev/null 2>&1
fi
echo -e "  ${GREEN}✅${NC} Thunderbird: Đã cài đặt"

if ping -c 1 -W 2 mail.bizflycloud.vn &> /dev/null; then
    echo -e "  ${GREEN}✅${NC} Internet: OK"
else
    echo -e "  ${RED}❌${NC} Internet: Không có kết nối"
    exit 1
fi
echo ""

# ============================================
# 2. NHẬP THÔNG TIN
# ============================================
echo -e "${BLUE}[2/5] 📝 Nhập thông tin cấu hình${NC}"

echo -e "\n  Chọn giao thức:"
echo -e "    ${GREEN}1${NC}. IMAP (Khuyến nghị)"
echo -e "    ${YELLOW}2${NC}. POP3"
read -p "  Lựa chọn [1/2]: " CHOICE

if [ "$CHOICE" = "2" ]; then
    PROTO="pop3"; PORT="995"
else
    PROTO="imap"; PORT="993"
fi

echo ""
read -p "  Tên hiển thị: " FULL_NAME
while [ -z "$FULL_NAME" ]; do
    read -p "  Tên hiển thị (không để trống): " FULL_NAME
done

echo ""
read -p "  Email: " USER_EMAIL
while [[ ! "$USER_EMAIL" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; do
    read -p "  Email (hợp lệ): " USER_EMAIL
done

echo ""
read -s -p "  Mật khẩu (để trống nếu không lưu): " USER_PASS
echo ""
echo ""

# ============================================
# 3. TẠO PROFILE TRƯỚC KHI CẤU HÌNH
# ============================================
echo -e "${BLUE}[3/5] 📁 Tạo profile...${NC}"

# Xác định thư mục Thunderbird
TB_DIR="$HOME/.thunderbird"
if [ -d "$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird" ]; then
    TB_DIR="$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird"
fi

# Đóng Thunderbird
pkill thunderbird 2>/dev/null || true
sleep 2

# Tạo profile name
PROFILE_NAME="bizfly_$(date +%s)"

# Tạo profile bằng Thunderbird
echo -e "  ${YELLOW}⏳${NC} Tạo profile: $PROFILE_NAME"
thunderbird -CreateProfile "$PROFILE_NAME" > /dev/null 2>&1
sleep 3

# Tìm đường dẫn profile thực tế
PROFILE_PATH=$(find "$TB_DIR" -maxdepth 1 -type d -name "*.${PROFILE_NAME}" | head -1)

if [ -z "$PROFILE_PATH" ]; then
    echo -e "  ${RED}❌${NC} Không tìm thấy profile, tạo thủ công..."
    PROFILE_PATH="$TB_DIR/${PROFILE_NAME}"
    mkdir -p "$PROFILE_PATH"
fi

echo -e "  ${GREEN}✅${NC} Profile: $(basename "$PROFILE_PATH")"
echo ""

# ============================================
# 4. CẤU HÌNH VÀO ĐÚNG FILE
# ============================================
echo -e "${BLUE}[4/5] ⚙️  Cấu hình...${NC}"

# --- Tạo file prefs.js (QUAN TRỌNG) ---
echo -e "  ${YELLOW}⏳${NC} Tạo prefs.js..."

cat > "$PROFILE_PATH/prefs.js" <<EOF
# Mozilla User Preferences
/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */

user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");

user_pref("mail.identity.id1.fullName", "$FULL_NAME");
user_pref("mail.identity.id1.useremail", "$USER_EMAIL");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.smtpServer", "smtp1");

user_pref("mail.server.server1.type", "$PROTO");
user_pref("mail.server.server1.hostname", "mail.bizflycloud.vn");
user_pref("mail.server.server1.port", $PORT);
user_pref("mail.server.server1.userName", "$USER_EMAIL");
user_pref("mail.server.server1.authMethod", 3);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.name", "$USER_EMAIL");

user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "mail.bizflycloud.vn");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.username", "$USER_EMAIL");
EOF

# --- Tạo file user.js (BACKUP) ---
echo -e "  ${YELLOW}⏳${NC} Tạo user.js..."

cat > "$PROFILE_PATH/user.js" <<EOF
// Thunderbird BizFly Configuration
user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");

user_pref("mail.identity.id1.fullName", "$FULL_NAME");
user_pref("mail.identity.id1.useremail", "$USER_EMAIL");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.smtpServer", "smtp1");

user_pref("mail.server.server1.type", "$PROTO");
user_pref("mail.server.server1.hostname", "mail.bizflycloud.vn");
user_pref("mail.server.server1.port", $PORT);
user_pref("mail.server.server1.userName", "$USER_EMAIL");
user_pref("mail.server.server1.authMethod", 3);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.name", "$USER_EMAIL");

user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "mail.bizflycloud.vn");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.username", "$USER_EMAIL");

// Bỏ qua Setup Wizard - QUAN TRỌNG
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.configured", true);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.autoconfigured", true);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.hostname", "mail.bizflycloud.vn");
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.port", $PORT);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.socketType", 3);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.authMethod", 3);
user_pref("mail.auto_config.${USER_EMAIL}.done", true);
user_pref("mail.auto_config.${USER_EMAIL}.success", true);
EOF

# --- Tạo file logins.json (lưu mật khẩu) ---
if [ -n "$USER_PASS" ]; then
    echo -e "  ${YELLOW}⏳${NC} Lưu mật khẩu..."
    
    cat > "$PROFILE_PATH/logins.json" <<EOF
{
  "logins": [{
    "id": 1,
    "hostname": "mail.bizflycloud.vn",
    "username": "$USER_EMAIL",
    "password": "$USER_PASS"
  }],
  "version": 3
}
EOF
fi

# --- Tạo file panacea.dat (đánh dấu đã cấu hình) ---
touch "$PROFILE_PATH/panacea.dat"

# --- Cập nhật profiles.ini ---
echo -e "  ${YELLOW}⏳${NC} Cập nhật profiles.ini..."

cat > "$TB_DIR/profiles.ini" <<EOF
[General]
StartWithLastProfile=1
Version=2

[Profile0]
Name=$PROFILE_NAME
IsRelative=1
Path=$(basename "$PROFILE_PATH")
Default=1

[Install]
Default=Profiles/$PROFILE_NAME
EOF

echo -e "  ${GREEN}✅${NC} Cấu hình hoàn tất"
echo ""

# ============================================
# 5. HOÀN TẤT
# ============================================
echo -e "${BLUE}[5/5] 🎉 Hoàn tất${NC}"

echo -e "\n  ${GREEN}✅ CẤU HÌNH HOÀN TẤT!${NC}"
echo -e "\n  📋 Thông tin:"
echo -e "    • Giao thức: ${PROTO^^}"
echo -e "    • Server: mail.bizflycloud.vn:$PORT"
echo -e "    • Email: $USER_EMAIL"
echo -e "    • Profile: $PROFILE_NAME"
echo -e "    • Mật khẩu: $([ -n "$USER_PASS" ] && echo "${GREEN}Đã lưu${NC}" || echo "${YELLOW}Chưa lưu${NC}")"

echo -e "\n  ${GREEN}▶${NC} Mở Thunderbird..."
sleep 2

# Mở Thunderbird với profile
nohup thunderbird -P "$PROFILE_NAME" > /dev/null 2>&1 &
disown

echo -e "\n  ${GREEN}✅${NC} Thunderbird đã mở!"
echo -e "  ${GREEN}✅${NC} Email đã được cấu hình sẵn!"
echo -e "  ${GREEN}✅${NC} KHÔNG hiện Setup Wizard!"
echo -e "\n${BLUE}════════════════════════════════════════════════════════════${NC}\n"

exit 0
