#!/bin/bash
set -e

# ============================================
# Thunderbird BizFly Auto-Config Installer
# Version: 3.0
# ============================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

clear
echo -e "${BLUE}=========================================================${NC}"
echo -e "${BLUE}     THUNDERBIRD BIZFLY AUTO-CONFIG INSTALLER${NC}"
echo -e "${BLUE}                  Version 3.0${NC}"
echo -e "${BLUE}=========================================================${NC}\n"

# ============================================
# 1. Kiểm tra môi trường
# ============================================
echo -e "${BLUE}[1/5] Kiểm tra môi trường...${NC}"

# Kiểm tra và cài đặt Thunderbird
if ! command -v thunderbird &> /dev/null; then
    echo -e "  ${YELLOW}⚠${NC} Thunderbird chưa cài đặt, đang tiến hành cài đặt..."
    sudo apt update -qq
    sudo apt install -y thunderbird > /dev/null 2>&1
fi
echo -e "  ${GREEN}✓${NC} Thunderbird: Đã cài đặt"

# Kiểm tra kết nối
if ping -c 1 -W 2 mail.bizflycloud.vn &> /dev/null; then
    echo -e "  ${GREEN}✓${NC} Internet: OK"
else
    echo -e "  ${RED}✗${NC} Internet: Không có kết nối"
    exit 1
fi
echo ""

# ============================================
# 2. Nhập thông tin
# ============================================
echo -e "${BLUE}[2/5] Nhập thông tin cấu hình${NC}"

# Chọn giao thức
echo -e "\n  Chọn giao thức:"
echo -e "    ${GREEN}1${NC}. IMAP ${GREEN}(Khuyến nghị)${NC}"
echo -e "    ${YELLOW}2${NC}. POP3"
echo ""
read -p "  Lựa chọn [1/2] (Mặc định: 1): " PROTO_CHOICE
PROTO_CHOICE=${PROTO_CHOICE:-1}

if [ "$PROTO_CHOICE" = "2" ]; then
    SERVER_TYPE="pop3"
    IN_HOST="mail.bizflycloud.vn"
    IN_PORT="995"
else
    SERVER_TYPE="imap"
    IN_HOST="mail.bizflycloud.vn"
    IN_PORT="993"
fi

# Nhập tên
echo ""
while [ -z "$FULL_NAME" ]; do
    read -p "  Tên hiển thị: " FULL_NAME
    [ -z "$FULL_NAME" ] && echo -e "  ${RED}✗${NC} Không được để trống"
done

# Nhập email
echo ""
while [[ ! "$USER_EMAIL" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; do
    read -p "  Địa chỉ email: " USER_EMAIL
    [[ ! "$USER_EMAIL" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]] && \
        echo -e "  ${RED}✗${NC} Email không hợp lệ"
done

# Nhập mật khẩu (ẩn)
echo ""
read -s -p "  Mật khẩu email: " USER_PASSWORD
echo ""
if [ -z "$USER_PASSWORD" ]; then
    echo -e "  ${YELLOW}⚠${NC} Mật khẩu để trống, sẽ yêu cầu nhập khi mở Thunderbird"
fi

echo -e "\n  ${GREEN}✓${NC} Thông tin đã nhận:"
echo -e "    • Giao thức: ${SERVER_TYPE^^}"
echo -e "    • Tên: $FULL_NAME"
echo -e "    • Email: $USER_EMAIL"
echo -e "    • Mật khẩu: $([ -n "$USER_PASSWORD" ] && echo "Đã nhập" || echo "Chưa nhập")"
echo ""

# ============================================
# 3. Tạo profile và cấu hình
# ============================================
echo -e "${BLUE}[3/5] Cấu hình Thunderbird...${NC}"

# Xác định thư mục Thunderbird
TB_BASE="$HOME/.thunderbird"
if [ -d "$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird" ]; then
    TB_BASE="$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird"
    echo -e "  ${YELLOW}ℹ${NC} Sử dụng Thunderbird Snap"
fi

# Đóng Thunderbird
pkill -x thunderbird 2>/dev/null || true
sleep 2

# Tạo profile mới
PROFILE_NAME="bizfly_$(date +%s)"
echo -e "  ${YELLOW}⏳${NC} Tạo profile mới..."

# Xóa profile cũ
find "$TB_BASE" -maxdepth 1 -type d -name "*.bizfly_*" -exec rm -rf {} \; 2>/dev/null || true

# Tạo profile
thunderbird -CreateProfile "$PROFILE_NAME" > /dev/null 2>&1
sleep 2

# Tìm đường dẫn profile
PROFILE_PATH=$(find "$TB_BASE" -maxdepth 1 -type d -name "*.${PROFILE_NAME}" | head -n 1)

if [ -z "$PROFILE_PATH" ]; then
    echo -e "  ${YELLOW}⚠${NC} Tạo profile thủ công..."
    PROFILE_PATH="$TB_BASE/${PROFILE_NAME}.default"
    mkdir -p "$PROFILE_PATH"
fi

echo -e "  ${GREEN}✓${NC} Profile: $(basename "$PROFILE_PATH")"

# ============================================
# 4. Tạo file cấu hình
# ============================================
echo -e "\n${BLUE}[4/5] Tạo cấu hình email...${NC}"

# Tạo file prefs.js (quan trọng để Thunderbird tự động nhận diện)
cat <<'EOF' > "$PROFILE_PATH/prefs.js"
# Mozilla User Preferences
/* Do not edit this file.
 *
 * If you make changes to this file while the application is running,
 * the changes will be overwritten when the application exits.
 *
 * To make a manual change to preferences, you can visit the URL about:config
 */
EOF

# Tạo file user.js
cat <<EOF > "$PROFILE_PATH/user.js"
// ============================================
// Thunderbird Auto-Configuration for BizFly
// ============================================

// ---- ACCOUNT MANAGEMENT ----
user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.accountmanager.locallyStoredAccounts", "account1");

// ---- ACCOUNT 1 ----
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");

// ---- IDENTITY 1 ----
user_pref("mail.identity.id1.fullName", "$FULL_NAME");
user_pref("mail.identity.id1.useremail", "$USER_EMAIL");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.identity.id1.reply_to", "$USER_EMAIL");
user_pref("mail.identity.id1.organization", "BizFly");

// ---- INCOMING SERVER ----
user_pref("mail.server.server1.type", "$SERVER_TYPE");
user_pref("mail.server.server1.hostname", "$IN_HOST");
user_pref("mail.server.server1.port", $IN_PORT);
user_pref("mail.server.server1.userName", "$USER_EMAIL");
user_pref("mail.server.server1.authMethod", 3);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.name", "$USER_EMAIL");
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.server.server1.check_new_mail", true);

// ---- SMTP SERVER ----
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "mail.bizflycloud.vn");
user_pref("mail.smtpserver.smtp1.port", 587);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.username", "$USER_EMAIL");

// ---- LƯU MẬT KHẨU (NẾU CÓ) ----
EOF

# Lưu mật khẩu nếu có
if [ -n "$USER_PASSWORD" ]; then
    # Tạo file signons.sqlite (lưu mật khẩu)
    echo -e "  ${YELLOW}⏳${NC} Lưu mật khẩu..."
    
    # Tạo file logins.json
    cat <<EOF > "$PROFILE_PATH/logins.json"
{
  "logins": [
    {
      "id": 1,
      "hostname": "mail.bizflycloud.vn",
      "httpRealm": null,
      "formSubmitURL": null,
      "usernameField": "",
      "passwordField": "",
      "encryptedUsername": "",
      "encryptedPassword": "",
      "username": "$USER_EMAIL",
      "password": "$USER_PASSWORD",
      "timesUsed": 0
    }
  ],
  "disabledHosts": [],
  "version": 3
}
EOF
fi

# Thêm vào user.js để bỏ qua setup wizard
cat <<'EOF' >> "$PROFILE_PATH/user.js"

// ---- BỎ QUA SETUP WIZARD ----
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.provider.${SERVER_TYPE}.${USER_EMAIL}.configured", true);
user_pref("mail.provider.${SERVER_TYPE}.${USER_EMAIL}.username", "${USER_EMAIL}");
user_pref("mail.provider.${SERVER_TYPE}.${USER_EMAIL}.password", "");
user_pref("mail.provider.${SERVER_TYPE}.${USER_EMAIL}.autoconfigured", true);
user_pref("mail.provider.${SERVER_TYPE}.${USER_EMAIL}.hostname", "${IN_HOST}");
user_pref("mail.provider.${SERVER_TYPE}.${USER_EMAIL}.port", ${IN_PORT});
user_pref("mail.provider.${SERVER_TYPE}.${USER_EMAIL}.socketType", 3);
user_pref("mail.provider.${SERVER_TYPE}.${USER_EMAIL}.authMethod", 3);

// ---- TẮT KIỂM TRA CẤU HÌNH TỰ ĐỘNG ----
user_pref("mail.auto_config.${USER_EMAIL}.done", true);
user_pref("mail.auto_config.${USER_EMAIL}.success", true);

// ---- CẤU HÌNH UI ----
user_pref("mail.identity.id1.draft_autosave", true);
user_pref("mail.identity.id1.draft_autosave_interval", 30);
user_pref("mail.identity.id1.archive_enabled", true);
user_pref("mail.openMessageBehavior.version", 1);

// ---- BẢO MẬT ----
user_pref("privacy.trackingprotection.enabled", true);
user_pref("privacy.trackingprotection.emailtracking.enabled", true);
user_pref("mailnews.pop3.biff_hide_advanced_toggle", true);
EOF

echo -e "  ${GREEN}✓${NC} Cấu hình đã tạo tại: $PROFILE_PATH/user.js"

# ============================================
# 5. Cập nhật profiles.ini
# ============================================
echo -e "\n${BLUE}[5/5] Cập nhật profiles.ini...${NC}"

cat <<EOF > "$TB_BASE/profiles.ini"
[General]
StartWithLastProfile=1
Version=2

[Profile0]
Name=$PROFILE_NAME
IsRelative=1
Path=$(basename "$PROFILE_PATH")
Default=1

[Install]
Default=Profiles/$PROFILE_NAME
EOF

# Thêm file profiles.ini cho Snap nếu cần
if [ -d "$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird" ]; then
    cp "$TB_BASE/profiles.ini" "$TB_BASE/../profiles.ini" 2>/dev/null || true
fi

echo -e "  ${GREEN}✓${NC} profiles.ini đã cập nhật"

# ============================================
# 6. Hoàn tất
# ============================================
echo -e "\n${BLUE}=========================================================${NC}"
echo -e "${GREEN}✅ CẤU HÌNH HOÀN TẤT!${NC}"
echo -e "${BLUE}=========================================================${NC}"

echo -e "\n  📋 Thông tin cấu hình:"
echo -e "    • Giao thức: ${SERVER_TYPE^^}"
echo -e "    • Server đến: $IN_HOST:$IN_PORT"
echo -e "    • Server đi: mail.bizflycloud.vn:587"
echo -e "    • Email: $USER_EMAIL"
echo -e "    • Profile: $PROFILE_NAME"

if [ -n "$USER_PASSWORD" ]; then
    echo -e "    • Mật khẩu: Đã lưu"
else
    echo -e "    • Mật khẩu: ${YELLOW}Chưa lưu${NC} (nhập khi mở Thunderbird)"
fi

echo -e "\n  ${YELLOW}ℹ${NC} Lưu ý:"
if [ -n "$USER_PASSWORD" ]; then
    echo -e "    • Mật khẩu đã được lưu, bạn sẽ KHÔNG cần nhập lại"
else
    echo -e "    • Lần đầu mở sẽ yêu cầu nhập mật khẩu"
fi
echo -e "    • Thunderbird sẽ KHÔNG hiện màn hình Setup Wizard"
echo -e "    • Tất cả cấu hình đã được tự động áp dụng"

echo -e "\n  ${GREEN}▶${NC} Đang mở Thunderbird..."
sleep 2

# Khởi động Thunderbird
nohup thunderbird -P "$PROFILE_NAME" > /dev/null 2>&1 &
disown

echo -e "\n  ${GREEN}✓${NC} Thunderbird đã mở với profile $PROFILE_NAME"
echo -e "  ${GREEN}✓${NC} Email đã được cấu hình sẵn"
echo -e "\n${BLUE}=========================================================${NC}\n"

exit 0
