#!/bin/bash

# ============================================
# THUNDERBIRD BIZFLY INSTALLER - FIXED v5.0
# SỬ DỤNG DEFAULTS/PROFILE
# ============================================

set -e

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

clear
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║     🚀 THUNDERBIRD BIZFLY INSTALLER v5.0                ║${NC}"
echo -e "${BLUE}║     ✅ FIX: SỬ DỤNG DEFAULTS/PROFILE                    ║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════╝${NC}"
echo ""

# ============================================
# 1. KIỂM TRA
# ============================================
echo -e "${BLUE}[1/5] 🔍 Kiểm tra môi trường...${NC}"

if ! command -v thunderbird &> /dev/null; then
    echo -e "  ${YELLOW}⚠️${NC} Đang cài Thunderbird..."
    sudo apt update -qq && sudo apt install -y thunderbird > /dev/null 2>&1
fi
echo -e "  ${GREEN}✅${NC} Thunderbird: OK"

if ping -c 1 -W 2 mail.bizflycloud.vn &> /dev/null; then
    echo -e "  ${GREEN}✅${NC} Internet: OK"
else
    echo -e "  ${RED}❌${NC} Không có kết nối"
    exit 1
fi
echo ""

# ============================================
# 2. NHẬP THÔNG TIN
# ============================================
echo -e "${BLUE}[2/5] 📝 Nhập thông tin${NC}"

echo -e "\n  Chọn giao thức:"
echo -e "    ${GREEN}1${NC}. IMAP"
echo -e "    ${YELLOW}2${NC}. POP3"
read -p "  Lựa chọn [1/2]: " CHOICE

if [ "$CHOICE" = "2" ]; then
    PROTO="pop3"; PORT="995"
else
    PROTO="imap"; PORT="993"
fi

echo ""
read -p "  Tên hiển thị: " FULL_NAME
while [ -z "$FULL_NAME" ]; do
    read -p "  Tên hiển thị (không để trống): " FULL_NAME
done

echo ""
read -p "  Email: " USER_EMAIL
while [[ ! "$USER_EMAIL" =~ ^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}$ ]]; do
    read -p "  Email (hợp lệ): " USER_EMAIL
done

echo ""
read -s -p "  Mật khẩu (để trống nếu không lưu): " USER_PASS
echo ""
echo ""

# ============================================
# 3. XÓA PROFILE CŨ
# ============================================
echo -e "${BLUE}[3/5] 📁 Xóa profile cũ...${NC}"

pkill thunderbird 2>/dev/null || true
sleep 2

# Xóa toàn bộ profile cũ
rm -rf ~/.thunderbird/*.bizfly_* 2>/dev/null || true
rm -rf ~/.thunderbird/default 2>/dev/null || true
rm -f ~/.thunderbird/profiles.ini 2>/dev/null || true

echo -e "  ${GREEN}✅${NC} Đã xóa profile cũ"
echo ""

# ============================================
# 4. TẠO PROFILE MỚI
# ============================================
echo -e "${BLUE}[4/5] ⚙️  Tạo profile mới...${NC}"

# Tạo profile với tên cố định
PROFILE_NAME="bizfly"
echo -e "  ${YELLOW}⏳${NC} Tạo profile: $PROFILE_NAME"

# Tạo profile
thunderbird -CreateProfile "$PROFILE_NAME" > /dev/null 2>&1
sleep 3

# Tìm profile path
TB_BASE="$HOME/.thunderbird"
if [ -d "$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird" ]; then
    TB_BASE="$HOME/.var/app/org.mozilla.Thunderbird/.thunderbird"
fi

PROFILE_PATH=$(find "$TB_BASE" -maxdepth 1 -type d -name "*.${PROFILE_NAME}" | head -1)

if [ -z "$PROFILE_PATH" ]; then
    echo -e "  ${RED}❌${NC} Không tìm thấy profile, tạo thủ công..."
    PROFILE_PATH="$TB_BASE/${PROFILE_NAME}.default"
    mkdir -p "$PROFILE_PATH"
fi

echo -e "  ${GREEN}✅${NC} Profile: $(basename "$PROFILE_PATH")"
echo ""

# ============================================
# 5. CẤU HÌNH - CÁCH ĐÚNG
# ============================================
echo -e "${BLUE}[5/5] ⚙️  Cấu hình...${NC}"

# Cách 1: Ghi trực tiếp vào prefs.js
echo -e "  ${YELLOW}⏳${NC} Ghi cấu hình vào prefs.js..."

cat > "$PROFILE_PATH/prefs.js" <<EOF
# Mozilla User Preferences
/* Do not edit this file. */

user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.identity.id1.fullName", "$FULL_NAME");
user_pref("mail.identity.id1.useremail", "$USER_EMAIL");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.server.server1.type", "$PROTO");
user_pref("mail.server.server1.hostname", "mail.bizflycloud.vn");
user_pref("mail.server.server1.port", $PORT);
user_pref("mail.server.server1.userName", "$USER_EMAIL");
user_pref("mail.server.server1.authMethod", 3);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.name", "$USER_EMAIL");
user_pref("mail.server.server1.login_at_startup", true);
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "mail.bizflycloud.vn");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.username", "$USER_EMAIL");
EOF

# Cách 2: Tạo user.js
echo -e "  ${YELLOW}⏳${NC} Ghi cấu hình vào user.js..."

cat > "$PROFILE_PATH/user.js" <<EOF
// Thunderbird BizFly Configuration
user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.identity.id1.fullName", "$FULL_NAME");
user_pref("mail.identity.id1.useremail", "$USER_EMAIL");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.server.server1.type", "$PROTO");
user_pref("mail.server.server1.hostname", "mail.bizflycloud.vn");
user_pref("mail.server.server1.port", $PORT);
user_pref("mail.server.server1.userName", "$USER_EMAIL");
user_pref("mail.server.server1.authMethod", 3);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.name", "$USER_EMAIL");
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "mail.bizflycloud.vn");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.username", "$USER_EMAIL");

// Bỏ qua Setup Wizard
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.configured", true);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.autoconfigured", true);
user_pref("mail.auto_config.${USER_EMAIL}.done", true);
user_pref("mail.auto_config.${USER_EMAIL}.success", true);
EOF

# Cách 3: Tạo file cấu hình trong thư mục default (QUAN TRỌNG)
echo -e "  ${YELLOW}⏳${NC} Tạo cấu hình mặc định..."

# Tạo thư mục defaults nếu chưa có
mkdir -p "$TB_BASE/defaults/profile"

cat > "$TB_BASE/defaults/profile/user.js" <<EOF
// Default configuration for all profiles
user_pref("mail.accountmanager.accounts", "account1");
user_pref("mail.accountmanager.defaultaccount", "account1");
user_pref("mail.account.account1.identities", "id1");
user_pref("mail.account.account1.server", "server1");
user_pref("mail.identity.id1.fullName", "$FULL_NAME");
user_pref("mail.identity.id1.useremail", "$USER_EMAIL");
user_pref("mail.identity.id1.valid", true);
user_pref("mail.identity.id1.smtpServer", "smtp1");
user_pref("mail.server.server1.type", "$PROTO");
user_pref("mail.server.server1.hostname", "mail.bizflycloud.vn");
user_pref("mail.server.server1.port", $PORT);
user_pref("mail.server.server1.userName", "$USER_EMAIL");
user_pref("mail.server.server1.authMethod", 3);
user_pref("mail.server.server1.socketType", 3);
user_pref("mail.server.server1.name", "$USER_EMAIL");
user_pref("mail.smtpservers", "smtp1");
user_pref("mail.smtp.defaultserver", "smtp1");
user_pref("mail.smtpserver.smtp1.hostname", "mail.bizflycloud.vn");
user_pref("mail.smtpserver.smtp1.port", 465);
user_pref("mail.smtpserver.smtp1.try_ssl", 3);
user_pref("mail.smtpserver.smtp1.authMethod", 3);
user_pref("mail.smtpserver.smtp1.username", "$USER_EMAIL");
user_pref("mail.startup.enabledMailCheckOnce", true);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.configured", true);
user_pref("mail.provider.${PROTO}.${USER_EMAIL}.autoconfigured", true);
user_pref("mail.auto_config.${USER_EMAIL}.done", true);
user_pref("mail.auto_config.${USER_EMAIL}.success", true);
EOF

# Lưu mật khẩu
if [ -n "$USER_PASS" ]; then
    echo -e "  ${YELLOW}⏳${NC} Lưu mật khẩu..."
    cat > "$PROFILE_PATH/logins.json" <<EOF
{
  "logins": [{
    "id": 1,
    "hostname": "mail.bizflycloud.vn",
    "username": "$USER_EMAIL",
    "password": "$USER_PASS"
  }],
  "version": 3
}
EOF
fi

# Cập nhật profiles.ini
cat > "$TB_BASE/profiles.ini" <<EOF
[General]
StartWithLastProfile=1
Version=2

[Profile0]
Name=$PROFILE_NAME
IsRelative=1
Path=$(basename "$PROFILE_PATH")
Default=1
EOF

echo -e "  ${GREEN}✅${NC} Cấu hình hoàn tất"
echo ""

# ============================================
# 6. HOÀN TẤT
# ============================================
echo -e "${GREEN}✅ CẤU HÌNH HOÀN TẤT!${NC}"
echo -e "\n  📋 Thông tin:"
echo -e "    • Giao thức: ${PROTO^^}"
echo -e "    • Server: mail.bizflycloud.vn:$PORT"
echo -e "    • Email: $USER_EMAIL"
echo -e "    • Profile: $PROFILE_NAME"

echo -e "\n  ${GREEN}▶${NC} Mở Thunderbird..."
sleep 2

nohup thunderbird -P "$PROFILE_NAME" > /dev/null 2>&1 &
disown

echo -e "\n  ${GREEN}✅${NC} Đã mở Thunderbird!"
echo -e "  ${YELLOW}ℹ️${NC} Nếu vẫn thấy Setup Wizard, hãy thử cách sau:"
echo -e "  ${YELLOW}ℹ️${NC} 1. Đóng Thunderbird"
echo -e "  ${YELLOW}ℹ️${NC} 2. Chạy: thunderbird -safe-mode"
echo -e "  ${YELLOW}ℹ️${NC} 3. Vào about:config, kiểm tra cấu hình"
echo ""

exit 0
